"""empty message

Revision ID: 504f1cd39d89
Revises: 7bf6119b76ed
Create Date: 2017-03-12 10:06:35.192292

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '504f1cd39d89'
down_revision = '7bf6119b76ed'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_profile', sa.Column('image', sa.String(length=50), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_profile', 'image')
    # ### end Alembic commands ###
