"""empty message

Revision ID: 66b0e90b7f2d
Revises: 6252e3daa359
Create Date: 2017-03-11 21:37:25.376240

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '66b0e90b7f2d'
down_revision = '6252e3daa359'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_profile', 'date')
    op.drop_column('user_profile', 'image')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_profile', sa.Column('image', postgresql.BYTEA(), autoincrement=False, nullable=True))
    op.add_column('user_profile', sa.Column('date', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
