"""empty message

Revision ID: 7bf6119b76ed
Revises: d5ed23bc4175
Create Date: 2017-03-12 10:06:12.968191

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7bf6119b76ed'
down_revision = 'd5ed23bc4175'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_profile', 'image')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_profile', sa.Column('image', sa.VARCHAR(length=20), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
